language: node_js
node_js:
- '10'
- '12'
if: "(branch != master AND type = pull_request) OR (branch = master AND commit_message !~ /^Release v/) OR tag =~ ^v"
stages:
- test
- Build and Tag
- deploy
script:
- npm run lint
- npm run test:unit
env:
- GH_REPOSITORY=gamaops/hfx-bus
jobs:
  include:
  - stage: Build and Tag
    node_js: '12'
    name: Build and Tag
    script:
    - ".travis/semver.sh"
    if: tag !~ ^v AND branch = master AND type = push
  - stage: deploy
    deploy:
      provider: npm
      skip_cleanup: true
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      on:
        tags: true
    if: tag =~ ^v AND branch != master AND type = push
notifications:
  slack:
    rooms:
    - secure: "VaRyshPfDUcsk7rRKlcFOOme6gt0Pie2s5g50Yl2ZZkgIloDexfmyo2ggQnfE2lEzUYGGrIG0nNBqmxa/nk3zQPBwZ3OEtr/FK8bUlRGKn4nPCevY7yVIM6V1MOxXEE3/jnJoL9gy6hd43cJtJXPWenCeZ7UdpDzM9qZb7xRkioiGYhYXs5rZjvdU3T1nShZivlKIVtm7FWOJwbYMaSf2AZf+cn786BwT6R/9/alIPUs8MuoNiP49kL8cv+gEllK8EFTIYYShDwW5kQ/AirFJI6StYPMuf9MJD62bjBMC1bGmMl77wzQF3uGAxAzqxi9EhD6vZZ2oSRJxX5GQXkx/snDicKPSW/O+chnOMUeCdMm9oVsYIE1k6MCg4yWnErXkhOUfT0S1MTzXceem0dpOAImue4RIsL6wymOwcDgBXYzMPwqSuBUVOPkkFAUM5s2RsfKhkTRNAmqPpczPj85lrkh6zyKEeuIhBt2wPqYiZEHqqabHUVWxa/3z6DI0r+IPmixZ+8nN+Sl9NBDaXN4z9NUil+RbDP/MB7JMpStCOzCPkuqEiI6BWUDbKe0cSvLsr4eUQ3/qRGC7T9VrDUpA32KdPNTX5eGPLgN04rrAadFQ8RZBFdwmWzUOi+er0Ad/46JO873UsUx2Ne5+czXtvPxjOV2xqV0tJygSGyA6oE="
    on_success: always
    on_failure: always
    on_pull_requests: true
